### ISSUE TITLE
Link to wrong GitHub repository

### ISSUE THREAD

**Issue by chaoran-chen** [pathoplexus/example_data#2]
On https://pathoplexus.github.io/example_data/, the GitHub icon links to the https://github.com/loculus-project/example_data and not to this repository.

**Comment by theosanderson** [comment]
I just spotted this too! :o

**Comment by theosanderson** [comment]
I pushed a fix to main - which I didn't actually mean to - I'll set up branch protection now

**Comment by theosanderson** [comment]
(Thanks for raising)

**Comment by theosanderson** [comment]
And I made a typo, will make a PR to fix
